### ISSUE TITLE
Is it necessary to send a hash amount in a frontend transaction

### ISSUE THREAD

**Issue by poludnev** [NotarizedScreenshot/external-adapter#37]
There is an NFT identifier that we are minting. It is a bigint, which we get from the hash sum of the content. We send the same hash amount in transactions from the frontend. The chainlink node compares these two hash sums and, if they do not match, refuses to change the NFT.
We need to understand whether we will send this hash amount in transactions from the frontend.
If we don't, then we need to change the settings of the Chainlink node (?).
If we do, we need to formulate we will receive this hash sum.

**Comment by utgarda** [comment]
As discussed in  #29  
we need to separate all the heavy lifting - namely uploading media from Twitter to IPFS 
and generating confirmations on Chainlink nodes. So the screenshot will be done quite ahead of minting.

That's why the user should be able to preview what is being minted, and explicitly confirm that what has been uploaded to IPFS is what the user wants to be notarized. That means the transaction  has to contain that confirmation, and that's Merkle root (top level hash) of all the related content.
